customer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('diseases/', include('disease_database.urls')),
    path('bookings/', include('bookings.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import (LoginpageView, ProfileView, ProfileViewPK, DoctorSignupView, PatientSignupView,
                    PatientProfileUpdateView, DoctorProfileUpdateView, ChangePasswordView)

app_name = 'users'

urlpatterns = [
    path('login/', LoginpageView, name='login'),

    path('logout/', auth_views.LogoutView.as_view(next_page='/accounts/login'), name='logout'),

    path('profile/', login_required(ProfileView, login_url='users:login'), name='profile'),
    path('profile/<int:pk>/', login_required(ProfileViewPK, login_url='users:login'), name='profile_with_pk'),
    # path('Dprofile', login_required(ProfileView), name='Dprofile'),

    path('doctor/registration/', DoctorSignupView, name='doctor_registration'),
    path('patient/registration/', PatientSignupView, name='patient_registration'),

    path('Patient/update/', login_required(PatientProfileUpdateView, login_url='users:login'), name='Pupdateprofile'),
    path('Doctor/update/', login_required(DoctorProfileUpdateView, login_url='users:login'), name='Dupdateprofile'),

    path('change_password/', login_required(ChangePasswordView, login_url='users:login'), name='ChangePassword'),
]

users/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator
import datetime


class UserManager(BaseUserManager):

    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('Users must have an email address')
        now = timezone.now()
        email = self.normalize_email(email)
        user = self.model(
            email=email,
            is_staff=False,
            is_active=True,
            is_superuser=False,
            last_login=now,
            date_joined=now,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, name, password):
        if not email:
            raise ValueError('Users must have an email address')
        now = timezone.now()
        email = self.normalize_email(email)
        user = self.model(
            email=email,
            name=name,
            is_staff=True,
            is_active=True,
            is_superuser=True,
            last_login=now,
            date_joined=now,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    states = (
              ('AndhraPradesh', 'Andhra Pradesh'),
              ('ArunachalPradesh', 'Arunachal Pradesh'),
              ('Assam', 'Assam'),
              ('Sikkim', 'Sikkim'),
              ('Nagaland', 'Nagaland'),
              ('Manipur', 'Manipur'),
              ('Meghalaya', 'Meghalaya'),
              ('Jammukashmir', 'Jammu kashmir'),
              ('Punjab', 'Punjab'),
              ('Himachalpradesh', 'Himachal pradesh'),
              ('Haryana', 'Haryana'),
              ('Uttarakhand', 'Uttarakhand'),
              ('Uttarpradesh', 'Uttar pradesh'),
              ('Rajasthan', 'Rajasthan'),
              ('Gujarat', 'Gujarat'),
              ('MadhyaPradesh', 'Madhya Pradesh'),
              ('Jharkhand', 'Jharkhand'),
              ('WestBengal', 'West Bengal'),
              ('Maharastra', 'Maharastra'),
              ('Orissa', 'Orissa'),
              ('Chattisgarh', 'Chattisgarh'),
              ('Karnataka', 'Karnataka'),
              ('Kerala', 'Kerala'),
              ('TamilNadu', 'Tamil Nadu'),
              ('Mizoram', 'Mizoram'),
              ('Tripura', 'Tripura'),
              ('Goa', 'Goa'),
              ('Telangana', 'Telangana'),
              )
    email = models.EmailField(max_length=254, unique=True)
    name = models.CharField(max_length=254, null=True)

    is_doctor = models.BooleanField(default=False, null=True)
    is_patient = models.BooleanField(default=False, null=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=50, null=True)
    pin = models.PositiveIntegerField(null=True)
    state = models.CharField(max_length=25, choices=states, null=True)

    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    last_login = models.DateTimeField(null=True, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    def __str__(self):
        return self.email

    def doc_email(self):
        return self.email


class ExtendedDoctorsDetail(models.Model):
    specializations = (('Dermatologists', 'Dermatologists'),
                       ('Family Physicians', 'Family Physicians'),
                       ('Gastroenterologists', 'Gastroenterologists'),
                       ('Allergy & Immunologist', 'Allergy & Immunologist'),
                       ('Anesthesiologist', 'Anesthesiologist'),
                       ('Emergency Physicians', 'Emergency Physicians'),
                       ('Internist Physicians', 'Internist Physicians'),
                       ('Neurologist', 'Neurologist'),
                       ('Gynecologist/Obstetrician', 'Gynecologist/Obstetrician'),
                       ('Opthalmologist', 'Opthalmologist'),
                       ('Pediatrics', 'Pediatrics'),
                       ('Psychiatrist', 'Psychiatrist'),
                       ('Urologist', 'Urologist'))

    doctor = models.OneToOneField(User, on_delete=models.CASCADE, related_name='doctor_detail', primary_key=True)
    specialization = models.CharField(max_length=50, choices=specializations, null=True)
    is_verified = models.BooleanField(default=False, blank=True, null=True)

    def __str__(self):
        return self.doctor.email


class ExtendedPatientsDetail(models.Model):
    gender = (('Male', 'Male'),
              ('Female', 'Female'),
              ('Other', 'Other'))
    patient = models.OneToOneField(User, on_delete=models.CASCADE, related_name='patient_detail', primary_key=True)
    age = models.IntegerField(null=True, validators=[MaxValueValidator(120), MinValueValidator(1)])
    gender = models.CharField(max_length=20, choices=gender, null=True)

    def __str__(self):
        return self.patient.email


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created and instance.is_doctor:
        ExtendedDoctorsDetail.objects.create(doctor=instance)
    elif created and instance.is_patient:
        ExtendedPatientsDetail.objects.create(patient=instance)

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from .models import User, ExtendedDoctorsDetail, ExtendedPatientsDetail


class UserSignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2', 'name', 'address', 'city', 'pin', 'state')


class ExtendedDoctorsDetailForm(forms.ModelForm):
    # open_time = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time'}, format='%H:%M'))
    # close_time = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time'}, format='%H:%M'))
    class Meta:
        model = ExtendedDoctorsDetail
        fields = ('specialization',)


class ExtendedPatientsDetailForm(forms.ModelForm):
    class Meta:
        model = ExtendedPatientsDetail
        fields = ('age', 'gender')

# to update user profile


class UpdateUserProfile(UserChangeForm):
    class Meta:
        model = User
        fields = ('name', 'address', 'city', 'pin', 'state')


class UpdateDoctorProfile(forms.ModelForm):
    # open_time = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time'}, format='%H:%M'))
    # close_time = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time'}, format='%H:%M'))

    class Meta:
        model = ExtendedDoctorsDetail
        fields = ('specialization',)


class UpdatePatientProfile(forms.ModelForm):
    class Meta:
        model = ExtendedPatientsDetail
        fields = ('age', 'gender')

users/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from .forms import (UserSignUpForm, ExtendedDoctorsDetailForm, ExtendedPatientsDetailForm,
                    UpdateUserProfile, UpdatePatientProfile, UpdateDoctorProfile)
from .decorators import patient_required, doctor_required
from .models import User


def LoginpageView(request):
    if request.user.is_authenticated:
        if request.user.is_patient:
            return redirect('disease_database:search')
        elif request.user.is_doctor:
            return redirect('bookings:show_appointment_doctor')
    elif request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            if user.is_patient:
                return redirect('disease_database:search')
            elif user.is_doctor:
                return redirect('bookings:show_appointment_doctor')
        else:
            messages.error(request, 'Username or Password is invalid')
            return redirect('/accounts/login/')
    return render(request, 'home.html')


def ProfileViewPK(request):
    pass


def ProfileView(request):
    user = request.user
    if user is None:
        return render(request, 'login.html')
    args = {'user': user}
    if user.is_patient:
        return render(request, 'patient_profile.html', args)
    elif user.is_doctor:
        return render(request, 'doctor_profile.html', args)
    else:
        return render(request, 'home.html')


def DoctorSignupView(request):
    dr_template = 'doctor_registration.html'
    if request.method == 'POST':

        user_form = UserSignUpForm(request.POST)
        doctor_form = ExtendedDoctorsDetailForm(request.POST)

        if user_form.is_valid() and doctor_form.is_valid():
            user = user_form.save(commit=False)
            user.is_doctor = True
            raw_password = user_form.cleaned_data.get('password1')
            user.save()
            # doctor_form.save(commit=False)
            user.doctor_detail.specialization = doctor_form.cleaned_data.get('specialization')
            user.doctor_detail.total_book_per_day = doctor_form.cleaned_data.get('total_book_per_day')
            if doctor_form.cleaned_data.get('specialization') is not None:
                user.doctor_detail.is_verified = True
            user.doctor_detail.save()
            user = authenticate(request, email=user.email, password=raw_password)
            if user is not None:
                messages.success(request, 'Successfully Registered !!')
                return redirect('/accounts/login/')
            else:
                return render(request, dr_template)
        messages.error(request, "Invalid Form")
        return render(request, dr_template, {'user_form': user_form, 'doctor_form': doctor_form})
    else:
        user_form = UserSignUpForm()
        doctor_form = ExtendedDoctorsDetailForm()
    return render(request, dr_template, {'user_form': user_form, 'doctor_form': doctor_form})


def PatientSignupView(request):
    pr_template = 'patient_registration.html'
    if request.method == 'POST':
        user_form = UserSignUpForm(request.POST)
        patient_form = ExtendedPatientsDetailForm(request.POST)

        if user_form.is_valid() and patient_form.is_valid():
            user = user_form.save(commit=False)
            user.is_patient = True
            raw_password = user_form.cleaned_data.get('password1')
            user.save()
            user.patient_detail.age = patient_form.cleaned_data.get('age')
            user.patient_detail.gender = patient_form.cleaned_data['gender']
            user.patient_detail.save()
            user = authenticate(request, email=user.email, password=raw_password)
            if user is not None:
                messages.success(request, 'Successfully registered as Patient')
                return redirect('/accounts/login/')
            else:
                messages.error(request, "User in not Registered")
                return render(request, pr_template)
        messages.error(request, "Form is invalid")
        return render(request, pr_template, {'user_form': user_form, 'patient_form': patient_form})
    else:
        user_form = UserSignUpForm()
        patient_form = ExtendedPatientsDetailForm()
        return render(request, pr_template, {'user_form': user_form, 'patient_form': patient_form})


@doctor_required()
def DoctorProfileUpdateView(request):
    dpu_template = 'doctor_profile_update.html'
    if request.method == 'POST':
        update_user_form = UpdateUserProfile(request.POST, instance=request.user)
        update_doctor_form = UpdateDoctorProfile(request.POST, instance=request.user.doctor_detail)
        if update_user_form.is_valid() and update_doctor_form.is_valid():
            user = update_user_form.save(commit=False)
            user.is_doctor = True
            user.save()
            # doctor_form.save(commit=False)
            user.doctor_detail.specialization = update_doctor_form.cleaned_data.get('specialization')
            user.doctor_detail.total_book_per_day = update_doctor_form.cleaned_data.get('total_book_per_day')
            if update_doctor_form.cleaned_data.get('specialization') is not None:
                user.doctor_detail.is_verified = True
            user.doctor_detail.save()
            return redirect('/accounts/profile/')
        messages.error(request, "Form is invalid")
        return render(request, dpu_template, {'update_user_form': update_user_form, 'update_doctor_form': update_doctor_form})
    else:
        update_user_form = UpdateUserProfile(instance=request.user)
        update_doctor_form = UpdateDoctorProfile(instance=request.user.doctor_detail)
    return render(request, dpu_template,
                  {'update_user_form': update_user_form, 'update_doctor_form': update_doctor_form})


@patient_required()
def PatientProfileUpdateView(request):
    ppu_template = 'patient_profile_update.html'
    if request.method == 'POST':
        update_user_form = UpdateUserProfile(request.POST, instance=request.user)
        update_patient_form = UpdatePatientProfile(request.POST, instance=request.user.patient_detail)

        if update_user_form.is_valid() and update_patient_form.is_valid():
            user = update_user_form.save(commit=False)
            user.is_patient = True
            user.save()
            user.patient_detail.age = update_patient_form.cleaned_data.get('age')
            user.patient_detail.save()
            print(user.id)
            return redirect("/accounts/profile/")
        messages.error(request, "Form is invalid")
        return render(request, ppu_template)
    else:
        update_user_form = UpdateUserProfile(instance=request.user)
        update_patient_form = UpdatePatientProfile(instance=request.user.patient_detail)
        return render(request, ppu_template,
                      {'update_user_form': update_user_form, 'update_patient_form': update_patient_form})


def ChangePasswordView(request):
    if request.method == 'POST':
        change_password_form = PasswordChangeForm(data=request.POST, user=request.user)

        if change_password_form.is_valid():
            change_password_form.save()
            update_session_auth_hash(request, change_password_form.user)
            return redirect('/accounts/profile/')
        messages.error(request, "Form is invalid")
        return render(request, 'change_password.html', {'change_password_form': change_password_form})
    else:
        change_password_form = PasswordChangeForm(user=request.user)
        return render(request, 'change_password.html', {'change_password_form': change_password_form})

users/templates/doctor_profile.html
{% extends 'base.html' %}
{% block title %}
    <title>Doctor | Profile</title>
{% endblock %}
{% load static %}
{% block body %}
    {% include 'navBar.html' %}
    <div style=" background-image: url({% static 'images/doc-pat-ed.jpg' %}); width: 100%; height:90%; background-size: cover; background-attachment: fixed; background-position: center center;">
    <div class="container row">

        <div class="card col m9 s12" style="padding:10px; margin-top:20px;">
            <h4 style="font-style:bold; color:blue; font-weight:600;">Doctor Profile:</h4>
            <hr>
            <div class="container">
                <label style="font-size:15px;" for="id_name">Name:</label>
                <blockquote style="margin-top:0px; font-weight: 500; font-size:20px;">{{ user.name }}</blockquote>
                <label style="font-size:15px;" for="id_email">Email:</label>
                <blockquote style="margin-top:0px; font-weight: 500; font-size:20px;">{{ user.email }}</blockquote>
                <label style="font-size:15px;" for="id_address">Address:</label>
                <blockquote style="margin-top:0px; font-weight: 500; font-size:20px;">{{user.address}}</blockquote>
                <label style="font-size:15px;" for="id_city">City:</label>
                <blockquote style="margin-top:0px; font-weight: 500; font-size:20px;">{{user.city}}</blockquote>
                <label style="font-size:15px;" for="id_pin">Pin:</label>
                <blockquote style="margin-top:0px; font-weight: 500; font-size:20px;">{{user.pin}}</blockquote>
                <label style="font-size:15px;" for="id_state">State:</label>
                <blockquote style="margin-top:0px; font-weight: 500; font-size:20px;">{{user.state}}</blockquote>
                <label style="font-size:15px;" for="id_specialization">Specialization:</label>
                <blockquote style="margin-top:0px; font-weight: 500; font-size:20px;">{{ user.doctor_detail.specialization }}</blockquote>
            </div>
        </div>

        <div class="col s3">
            <div class="container center" style="padding-top:30px;">
                <a class="btn waves-effect waves-light blue" href="{% url 'users:Dupdateprofile' %}" style="margin:8px;">Edit Profile</a>
                <a class="btn l waves-effect waves-light blue" href="{% url 'users:ChangePassword' %}" style="margin:8px; width:180px;">Change Password</a>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

users/templates/doctor_registration.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    <title>Doctor | Registration</title>
{% endblock %}
{% load static %}
{% block body %}
    {% include 'navBar.html' %}
    <div class="container">
      <h4>Register as Doctor</h4>
        {% if messages %}
        {% for message in messages %}
          <div class="messages center" style="min-height:40px; background-color:white; border-radius:7px; margin: 0px 200px 10px 200px;">
            <span class="{{ message.tags }}"style="font-size: 20px; padding: 20px 50px;"> {{ message }}</span></div>
        {% endfor %}
        {% endif %}

        {% if user_form.errors %}
        {{ user_form.non_field_errors }}
        {% for field in user_form %}
            {% if field.errors %}
                <div class="messages center" style="min-height:35px; border: 2px solid red; border-radius:7px; margin: 0px 100px 10px 100px;">
                  <span style="font-size: 18px; padding: 20px 50px; color: red;">{{ field.errors|striptags }} ({{field.name}})</span></div>
            {% endif %}
        {% endfor %}
      {% endif %}
      {% if doctor_form.errors %}
        {{ doctor_form.non_field_errors }}
        {% for field in doctor_form %}
            {% if field.errors %}
                <div class="messages center" style="min-height:35px; border: 2px solid red; border-radius:7px; margin: 0px 100px 10px 100px;">
                  <span style="font-size: 18px; padding: 20px 50px; color: red;">{{ field.errors|striptags }} ({{field.name}})</span></div>
            {% endif %}
        {% endfor %}
      {% endif %}
      <div id="success"></div>
      <div class="row">
        <form class="col s6" id="RegistrationForm" method="POST" target="" novalidate>
          {% csrf_token %}
          <div>
            <div class="input-field">
              <label for="id_name">Full Name</label>
                {{ user_form.name }}
              <span class="helper-text"></span>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s12">
              <label for="id_email">Email</label>
              {{ user_form.email }}
              <span class="helper-text"></span>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s6">
              <label for="id_password1">Password</label>
              {{ user_form.password1 }}
              <span class="helper-text"></span>
            </div>
            <div class="input-field col s6">
              <label for="id_password2">Confirm Password</label>
              {{ user_form.password2 }}
              <span class="helper-text"></span>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s12">
              <label for="id_address">Local Address</label>
              {{ user_form.address }}
              <span class="helper-text"></span>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s4">
              <label for="id_city">City</label>
              {{ user_form.city }}
              <span class="helper-text"></span>
            </div>
            <div class="input-field col s3">
              <label for="id_pin">Pin</label>
              {{ user_form.pin }}
              <span class="helper-text"></span>
            </div>
            <div class="input-field col s5">
              <label for="id_state"></label>
              {{ user_form.state }}
              <span class="helper-text">Select State</span>
            </div>
          </div>

          <div class="row">
            <div class="input-field col s6">
              <label for="id_specialization"></label>
              {{ doctor_form.specialization }}
              <span class="helper-text">Select Specialization</span>
            </div>
          </div>

          <div class="row">
              <input class="col m4 z-depth-2" type="submit" value="Register" style="font-weight: 600; color: white; background-color: #008080; border:0px; border-radius:6px;  height:35px; margin: 10px 10px 30px 0px; ">
            <a href="{% url 'users:login' %}" class="waves-effect waves-light col m4 center"  style="font-weight: 600; color: #008080; background-color: white; border:2px solid #008080; border-radius:6px; height:35px; margin: 10px 10px 30px 10px; padding: 5px;">Login Page</a>
          </div>
        </form>
      </div>
    </div>
    <script src="{% static 'js/registration_script.js' %}"></script>
{% endblock %}

users/templates/patient_profile.html
{% extends 'base.html' %}
{% block title %}
    <title>Patient | Profile</title>
{% endblock %}
{% load static %}
{% block body %}
    {% include 'navBar.html' %}
    <div style=" background-image: url({% static 'images/doc-pat-ed.jpg' %}); width: 100%; height:90%; background-size: cover; background-attachment: fixed; background-position: center center;">

    <div class="container row">

        <div class="card col s9" style="padding:10px; margin-top:20px;">
            <h4 style="font-style:bold; color:blue; font-weight:600;">Patient Profile:</h4>
            <hr>
            <div class="container">
                <label style="font-size:15px;" for="id_name">Name:</label>
                <blockquote style="margin-top:0px; font-weight: 500; font-size:20px;">{{ user.name }}</blockquote>
                <label style="font-size:15px;" for="id_email">Email:</label>
                <blockquote style="margin-top:0px; font-weight: 500; font-size:20px;">{{ user.email }}</blockquote>
                <label style="font-size:15px;" for="id_address">Address:</label>
                <blockquote style="margin-top:0px; font-weight: 500; font-size:20px;">{{user.address}}</blockquote>
                <label style="font-size:15px;" for="id_city">City:</label>
                <blockquote style="margin-top:0px; font-weight: 500; font-size:20px;">{{user.city}}</blockquote>
                <label style="font-size:15px;" for="id_pin">Pin:</label>
                <blockquote style="margin-top:0px; font-weight: 500; font-size:20px;">{{user.pin}}</blockquote>
                <label style="font-size:15px;" for="id_state">State:</label>
                <blockquote style="margin-top:0px; font-weight: 500; font-size:20px;">{{user.state}}</blockquote>
                <label style="font-size:15px;" for="id_age">Age:</label>
                <blockquote style="margin-top:0px; font-weight: 500; font-size:20px;">{{ user.patient_detail.age }}</blockquote>
                <label style="font-size:15px;" for="id_gender">Gender:</label>
                <blockquote style="margin-top:0px; font-weight: 500; font-size:20px;">{{ user.patient_detail.gender }}</blockquote>

            </div>
        </div>

        <div class="col s3">
            <div class="container center" style="padding-top:30px;">
                <a class="btn waves-effect waves-light blue" href="{% url 'users:Pupdateprofile' %}" style="margin:8px;">Edit Profile</a>
                <a class="btn l waves-effect waves-light blue" href="{% url 'users:ChangePassword' %}" style="margin:8px; width:180px;">Change Password</a>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

users/templates/patient_registration.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    <title>Patient | Registration</title>
{% endblock %}
{% load static %}
{% block body %}
    {% include 'navBar.html' %}
    <div class="container">
      <h4>Register as Patient</h4>
      {% if messages %}
        {% for message in messages %}
          <div class="messages center" style="min-height:40px; background-color:white; border-radius:7px; margin: 0px 200px 10px 200px;">
            <span class="{{ message.tags }}"style="font-size: 20px; padding: 20px 50px;"> {{ message }}</span></div>
        {% endfor %}
        {% endif %}
      {% if user_form.errors %}
        {{ form.non_field_errors }}
        {% for field in form %}
            {% if field.errors %}
                <div class="messages center" style="min-height:35px; border: 2px solid red; border-radius:7px; margin: 0px 100px 10px 100px;">
                  <span style="font-size: 18px; padding: 20px 50px; color: red;">{{ field.errors|striptags }} ({{field.name}})</span></div>
            {% endif %}
        {% endfor %}
      {% endif %}

      {% if patient_form.errors %}
        {{ patient_.non_field_errors }}
        {% for field in patient_form %}
            {% if field.errors %}
                <div class="messages center" style="min-height:35px; border: 2px solid red; border-radius:7px; margin: 0px 100px 10px 100px;">
                  <span style="font-size: 18px; padding: 20px 50px; color: red;">{{ field.errors|striptags }} ({{field.name}})</span></div>
            {% endif %}
        {% endfor %}
      {% endif %}
      <div id="success"></div>
      <div class="row">
        <form class="col s6" id="RegistrationForm" method="POST" target="" novalidate>
          {% csrf_token %}
          <div>
            <div class="input-field">
              <label for="id_name">Full Name</label>
                {{ user_form.name }}
              <span class="helper-text"></span>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s12">
              <label for="id_email">Email</label>
              {{ user_form.email }}
              <span class="helper-text"></span>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s6">
              <label for="id_password1">Password</label>
              {{ user_form.password1 }}
              <span class="helper-text"></span>
            </div>
            <div class="input-field col s6">
              <label for="id_password2">Confirm Password</label>
              {{ user_form.password2 }}
              <span class="helper-text"></span>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s12">
              <label for="id_address">Local Address</label>
              {{ user_form.address }}
              <span class="helper-text"></span>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s4">
              <label for="id_city">City</label>
              {{ user_form.city }}
              <span class="helper-text"></span>
            </div>
            <div class="input-field col s3">
              <label for="id_pin">Pin</label>
              {{ user_form.pin }}
              <span class="helper-text"></span>
            </div>
            <div class="input-field col s5">
              <label for="id_state"></label>
              {{ user_form.state }}
              <span class="helper-text">Select State</span>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s6">
              <label for="id_age">Age</label>
              {{ patient_form.age }}
              <span class="helper-text"></span>
            </div>
            <div class="input-field col s6">
              <label for="id_gender"></label>
              {{ patient_form.gender }}
              <span class="helper-text">Select Gender</span>
            </div>
          </div>
          <div class="row">
              <input class="col m4 z-depth-2" type="submit" value="Register" style="font-weight: 600; color: white; background-color: #008080; border:0px; border-radius:6px;  height:35px; margin: 10px 10px 30px 0px; ">
            <a href="{% url 'users:login' %}" class="waves-effect waves-light col m4 center"  style="font-weight: 600; color: #008080; background-color: white; border:2px solid #008080; border-radius:6px; height:35px; margin: 10px 10px 30px 10px; padding: 5px;">Login Page</a>
          </div>
        </form>
      </div>
    </div>
    <script src="{% static 'js/registration_script.js' %}"></script>
{% endblock %}