bookings/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from .views import ShowAppointmentsDoctors, ShowAppointmentsPatients, bookingView, ModifyAppointmentDoctors, DeleteAppointmentView
app_name = 'bookings'

urlpatterns = [
    path('patient/', login_required(ShowAppointmentsPatients, login_url='users:login'), name='show_appointment_patient'),
    path('doctor/', login_required(ShowAppointmentsDoctors, login_url='users:login'), name='show_appointment_doctor'),
    path('', bookingView, name='conform_booking'),

    path('doctor/appointments/<str:pk>/', login_required(ModifyAppointmentDoctors, login_url='users:login'), name='modify_appointment_doctor'),
    path('patient/appointments/delete/<str:pk>/', login_required(DeleteAppointmentView, login_url='users:login'), name='delete_appointment'),
]

customer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('diseases/', include('disease_database.urls')),
    path('bookings/', include('bookings.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import (LoginpageView, ProfileView, ProfileViewPK, DoctorSignupView, PatientSignupView,
                    PatientProfileUpdateView, DoctorProfileUpdateView, ChangePasswordView)

app_name = 'users'

urlpatterns = [
    path('login/', LoginpageView, name='login'),

    path('logout/', auth_views.LogoutView.as_view(next_page='/accounts/login'), name='logout'),

    path('profile/', login_required(ProfileView, login_url='users:login'), name='profile'),
    path('profile/<int:pk>/', login_required(ProfileViewPK, login_url='users:login'), name='profile_with_pk'),
    # path('Dprofile', login_required(ProfileView), name='Dprofile'),

    path('doctor/registration/', DoctorSignupView, name='doctor_registration'),
    path('patient/registration/', PatientSignupView, name='patient_registration'),

    path('Patient/update/', login_required(PatientProfileUpdateView, login_url='users:login'), name='Pupdateprofile'),
    path('Doctor/update/', login_required(DoctorProfileUpdateView, login_url='users:login'), name='Dupdateprofile'),

    path('change_password/', login_required(ChangePasswordView, login_url='users:login'), name='ChangePassword'),
]

bookings/models.py
from django.db import models
from users.models import ExtendedDoctorsDetail, ExtendedPatientsDetail
# Create your models here.


class Booking(models.Model):
    status_options = (('Pending', 'Pending'),
                      ('Attended', 'Attended'))
    p_id = models.IntegerField(null=True)
    patient_name = models.CharField(max_length=30, null=True)
    patient_email = models.CharField(max_length=50, null=True)
    patient_age = models.CharField(max_length=2, null=True)

    d_id = models.IntegerField(null=True)
    doctor_name = models.CharField(max_length=30, null=True)
    doctor_email = models.CharField(max_length=50, null=True)
    specialization = models.CharField(max_length=50, null=True)
    city = models.CharField(max_length=100, null=True)

    booked_date = models.CharField(max_length=50, null=True)
    booked_time = models.CharField(max_length=50, null=True)

    doctors_advice = models.TextField(max_length=200, null=True, default='None')
    status = models.CharField(max_length=20, null=True, choices=status_options, default='Pending')

    '''def __str__(self):
        return self.patient_name'''

bookings/forms.py
from .models import Booking
from django import forms


class AppointmentBookingForm(forms.ModelForm):

    class Meta:
        model = Booking
        fields = ['p_id', 'patient_name', 'patient_email', 'd_id', 'doctor_name', 'doctor_email', 'specialization', 'city', 'booked_date', 'booked_time']


class ChangeStatusForm(forms.ModelForm):

    class Meta:
        model = Booking
        fields = ['status', 'doctors_advice']

bookings/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from users.models import ExtendedDoctorsDetail, User
from .dates import today_day as today_date

from .models import *
from users.decorators import patient_required, doctor_required
from .dates import time_list
from .forms import ChangeStatusForm


@patient_required()
def bookingView(request):
    specialist_list = list(ExtendedDoctorsDetail.objects.values_list('specialization', flat=True).distinct())
    cities_list = list(User.objects.filter(is_doctor=True).values_list('city', flat=True).distinct())
    if request.method == 'POST' and 'search_doctors' in request.POST:
        specialist = request.POST['specialist']
        city = request.POST['city']
        doctors_extd = ExtendedDoctorsDetail.objects.filter(specialization=specialist,
                                                            doctor__city__icontains=city).values('doctor',
                                                                                                 'specialization')
        doctors_base = User.objects.filter(doctor_detail__specialization=specialist,
                                           city__icontains=city).values('id', 'email', 'name',
                                                                        'address', 'city',
                                                                        'pin', 'state')
        for doctor_e in doctors_extd:
            for doctor_b in doctors_base:
                if doctor_e['doctor'] == doctor_b['id']:
                    doctor_b.update(doctor_e)
        filtered_results = doctors_base
        return render(request, 'bookings.html',
                      {'spcs': specialist_list, 'cities': cities_list, 'doctors': filtered_results,
                       'time_slots': time_list()})
    elif request.method == 'POST' and 'confirm-booking-button' in request.POST:
        date = request.POST.get('selected_date')
        time = request.POST.get('selected_time')
        print(date, time)
        booked_doctor_mail = request.POST.get('confirm-booking-button')
        doctors_extd = ExtendedDoctorsDetail.objects.filter(doctor__email=booked_doctor_mail).values('doctor',
                                                                                                     'specialization')
        doctors_base = User.objects.filter(email=booked_doctor_mail).values('id', 'name',
                                                                            'address', 'city')
        doctors_extd = doctors_extd[0]
        doctors_base = doctors_base[0]
        if Booking.objects.filter(doctor_email__icontains=booked_doctor_mail, booked_date__icontains=date, booked_time__icontains=time).count() < 1:
            book = Booking()
            book.p_id = request.user.id
            book.patient_name = request.user.name
            book.patient_email = request.user.email
            book.patient_age = request.user.patient_detail.age
            book.d_id = doctors_extd['doctor']
            book.doctor_name = doctors_base['name']
            book.doctor_email = booked_doctor_mail
            book.city = doctors_base['city']
            book.specialization = doctors_extd['specialization']
            book.booked_date = date
            book.booked_time = time
            book.save()
            messages.success(request,
                             'Successfully Booked Appointment. For date ' + date + ' with Doctor ' + doctors_base[
                                 'name'])
            return redirect('bookings:show_appointment_patient')
        else:
            messages.error(request, 'Time slot '+time+' is is not available, for Dr. '+doctors_base["name"]+', Please select another slot !!')
    context = {
        'spcs': specialist_list,
        'cities': cities_list,
    }
    return render(request, 'bookings.html', context)


@patient_required()
def ShowAppointmentsPatients(request):
    u_email = request.user.email
    bookings = Booking.objects.filter(patient_email=u_email).values().order_by('booked_date')
    return render(request, 'show_bookings_patient.html', {'bookings': bookings, 'today': today_date})


@doctor_required()
def ShowAppointmentsDoctors(request):
    u_email = request.user.email
    bookings = Booking.objects.filter(doctor_email=u_email).values().order_by('booked_date')
    return render(request, 'show_appointment_doctor.html', {'bookings': bookings, 'today': today_date, 'change_status_form': ChangeStatusForm})


@doctor_required()
def ModifyAppointmentDoctors(request, pk):
    booking = Booking.objects.get(id=pk)
    modify_form = ChangeStatusForm(instance=booking)
    if request.method == 'POST':
        modify_appointment_form = ChangeStatusForm(request.POST, instance=booking)
        if modify_appointment_form.is_valid():
            modify_appointment_form.save()
        return redirect('bookings:show_appointment_doctor')
    return render(request, 'modify_bookings.html', {'modify_form': modify_form})


@patient_required()
def DeleteAppointmentView(request, pk):
    try:
        Booking.objects.filter(id=pk).delete()
    except Booking.DoesNotExist:
        pass

    u_email = request.user.email
    bookings = Booking.objects.filter(patient_email=u_email).values().order_by('booked_date')
    return render(request, 'show_bookings_patient.html', {'bookings': bookings, 'today': today_date})

bookings/templates/modify_bookings.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    <title>Doctor | Appointments</title>
{% endblock %}
{% load static %}
{% block body %}
    {% include 'navBar.html' %}
    <div style=" background-image: url({% static 'images/doc-pat-ed.jpg' %});margin-top:0px; min-height: 90%; width: 100%; background-size: cover; background-attachment: fixed; background-position: center center;">
        <div class="container white" style="padding: 30px;">
            <center>
            <h5>Modify Appointment Details:</h5>
            <form method="post" target="">

                {% csrf_token %}
                <div class="">
                    <div class="">
                        <div class="" style="width: 100px;">
                            <label for="id_status">Status:</label>
                            {{modify_form.status}}
                        </div>
                        <div class="" style="height: 100px; width: 500px;">
                            <label for="id_sdoctors_advice">Your's Advice::</label>
                            {{modify_form.doctors_advice}}
                        </div>
                    </div>
                </div>
                <input  class="btn" type="submit" style="margin: 30px;" name="submit">
            </form>
                </center>
        </div>
    </div>
<script type="text/javascript">

    $(document).ready(function(){
        $('select').formSelect();
        $('.modal').modal();
    });


</script>
{% endblock %}

bookings/templates/show_appointment_doctor.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    <title>Doctor | Appointments</title>
{% endblock %}
{% load static %}
{% block body %}
    {% include 'navBar.html' %}
    <div style=" background-image: url({% static 'images/doc-pat-ed.jpg' %});margin-top:0px; min-height: 90%; width: 100%; background-size: cover; background-attachment: fixed; background-position: center center;">
    <div class="container white center" style="padding:10px; margin-top:0px;">
        <h4>Booked Appointments:</h4>
        {% if bookings %}
            <table style="border: solid 3px green;" class = "responsive-table striped bordered">
                <h5 style="color: green; font-weight:500; padding:4px; background-color: #89CFF0;">Appointments for Today:</h5>
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Patient's Name</th>
                    <th>Patient's Email</th>
                    <th>Patient's Age</th>
                    <th>Booked for Date</th>
                    <th>Time:</th>
                    <th>Status</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for k in bookings %}
                    {% if k.booked_date == today %}
                    {% if k.status == 'Attended' %}
                        <tr style="text-decoration: line-through;">
                        {% else %}
                        <tr>
                        {% endif %}
                        <td>{{ k.id }}</td>
                        <td>{{ k.patient_name }}</td>
                        <td>{{ k.patient_email }}</td>
                        <td>{{ k.patient_age }}</td>
                        <td>{{ k.booked_date }}</td>
                        <td>{{ k.booked_time }}</td>
                        <td>{{ k.status }}</td>
                        <td><a href="{% url 'bookings:modify_appointment_doctor' k.id %}" class="btn" id="{{k.id}}"><i class="material-icons">create</i></a></td>
                    </tr>

                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
            <table class = "responsive-table striped bordered">
                <h5 style="font-weight:500; padding:4px; background-color: #89CFF0;" >Upcoming Appointments:</h5>
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Patient's Name</th>
                    <th>Patient's Email</th>
                    <th>Patient's Age</th>
                    <th>Booked for Date</th>
                    <th>Time:</th>
                    <th>Status</th>
                </tr>
                </thead>
                <tbody>
                {% for k in bookings %}
                    {% if k.booked_date > today %}
                    <tr>
                        <td>{{ k.id }}</td>
                        <td>{{ k.patient_name }}</td>
                        <td>{{ k.patient_email }}</td>
                        <td>{{ k.patient_age }}</td>
                        <td>{{ k.booked_date }}</td>
                        <td>{{ k.booked_time }}</td>
                        <td>{{ k.status }}</td>
                    </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
            <table class = "responsive-table striped bordered">
                <h5 style="font-weight:500; padding:4px; background-color: #89CFF0;">Previous Appointments:</h5>
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Patient's Name</th>
                    <th>Patient's Email</th>
                    <th>Patient's Age</th>
                    <th>Booked for Date</th>
                    <th>Time:</th>
                    <th>Status</th>
                </tr>
                </thead>
                <tbody>
                {% for k in bookings reversed %}
                    {% if k.booked_date < today %}
                        {% if k.status == 'Attended' %}
                        <tr style="text-decoration: line-through;">
                        {% else %}
                        <tr>
                        {% endif %}
                        <td>{{ k.id }}</td>
                        <td>{{ k.patient_name }}</td>
                        <td>{{ k.patient_email }}</td>
                        <td>{{ k.patient_age }}</td>
                        <td>{{ k.booked_date }}</td>
                        <td>{{ k.booked_time }}</td>
                        <td>{{ k.status }}</td>
                    </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <h5 class="center">No Appointments are made for you!!</h5>
        {% endif %}
    </div>
    </div>
<script type="text/javascript">

    $(document).ready(function(){
        $('select').formSelect();
        $('.modal').modal();
    });


</script>
{% endblock %}

bookings/templates/show_bookings_patient.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    <title>Patient | Appointments</title>
{% endblock %}
{% load static %}
{% block body %}
    {% include 'navBar.html' %}
    <div style=" background-image: url({% static 'images/doc-pat-ed.jpg' %});margin-top:0px; min-height: 90%; width: 100%; background-size: cover; background-attachment: fixed; background-position: center center;">
    <div class="container white center" style="padding:10px; margin-top:0px;">
            {% if messages %}
                {% for message in messages %}
                    <p style="color: green; font-weight:500;">{{ message }}</p>
                {% endfor %}
            {% endif %}
        <div class="row">
        {% if bookings %}
        <div class="col s12">
        <!--ul class="tabs">
            <li class="tab col s4"><a href="#previous">Previous</a></li>
            <li class="tab col s4"><a class="active" href="#today">Today</a></li>
            <li class="tab col s4"><a href="#upcoming">Upcoming</a></li>
        </ul-->
        <div id="today active" class="s11">
            <table style="border: solid 3px green;" class = "responsive-table striped bordered">
                <h5 style="color: green; font-weight:500; padding: 5px; background-color: #89CFF0;">Today's Appointments:</h5>
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Doctors's Name</th>
                    <th>Doctor's Email</th>
                    <th>City</th>
                    <th>Specialist</th>
                    <th>Booked for Date</th>
                    <th>Time slot</th>
                    <th>Status</th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for k in bookings %}
                    {% if k.booked_date == today %}
                        {% if k.status == 'Attended' %}
                        <tr style="text-decoration: line-through;">
                        {% else %}
                        <tr>
                        {% endif %}
                        <td>{{ k.id }}</td>
                        <td>{{ k.doctor_name }}</td>
                        <td>{{ k.doctor_email }}</td>
                        <td>{{ k.city }}</td>
                        <td>{{ k.specialization }}</td>
                        <td>{{ k.booked_date }}</td>
                        <td>{{ k.booked_time }}</td>
                        <td>{{ k.status }}</td>
                        <td><button class="btn modal-trigger" data-md-tooltip="Doctors Advice" data-target="{{k.id}}"><i class="large material-icons large">description</i></button></td>
                        <td><button class="btn modal-trigger orange" data-md-tooltip="Delete"><i class="large material-icons large">delete_forever</i></button></td>
                    </tr>
                    <div id="{{k.id}}" class="modal">
                        <div class="modal-content">

                            {% if k.status == 'Pending' %}
                                <span style="font-size:15;">Status: <span style="color: orange;">{{ k.status }}</span></span>
                            {% else %}
                                <span style="font-size:15;">Status: <span style="color: green;">{{ k.status }}</span></span>
                            {% endif %}
                            <h4>Doctor's Advice:</h4>
                            <h5>{{ k.doctors_advice }}</h5>
                        </div>
                        <div class="modal-footer">
                          <a class="modal-action modal-close btn deep-orange darken-2">Close</a>
                        </div>
                    </div>

                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>

        <div id="upcoming" class="s11">
            <table class = "responsive-table striped bordered">
                <h5 style="font-weight:500; padding: 5px; background-color: #89CFF0;">Upcoming:</h5>
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Doctors's Name</th>
                    <th>Doctor's Email</th>
                    <th>City</th>
                    <th>Specialist</th>
                    <th>Booked for Date</th>
                    <th>Time slot</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for k in bookings %}
                    {% if k.booked_date > today %}
                    <tr>
                        <td>{{ k.id }}</td>
                        <td>{{ k.doctor_name }}</td>
                        <td>{{ k.doctor_email }}</td>
                        <td>{{ k.city }}</td>
                        <td>{{ k.specialization }}</td>
                        <td>{{ k.booked_date }}</td>
                        <td>{{ k.booked_time }}</td>
                        <td><a  class="btn modal-trigger orange" data-target="{{k.id}}del" data-md-tooltip="Delete"><i class="large material-icons">delete_forever</i></a></td>

                    </tr>
                        <div id="{{k.id}}del" class="modal">
                                <div class="modal-content">
                                    <span><h5>Are you sure, you want to delete this Appointment ?</h5></span>

                                </div>
                                <div class="modal-footer">
                                    <a class="modal-action modal-close btn deep-orange darken-2">No</a>
                                    <a href="{% url 'bookings:delete_appointment' k.id %}" class="modal-action modal-close btn teal darken-2">Yes</a>
                                </div>
                         </div>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>

        </div>
        <div id="previous" class="s11">
            <table class = "responsive-table striped bordered">
                <h5 style="font-weight:500; padding: 5px; background-color: #89CFF0;">Previous Bookings:</h5>
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Doctors's Name</th>
                    <th>Doctor's Email</th>
                    <th>City</th>
                    <th>Specialist</th>
                    <th>Booked for Date</th>
                    <th>Time slot</th>

                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for k in bookings reversed%}
                    {% if k.booked_date < today %}
                        {% if k.status != 'Pending' %}
                        <tr style="text-decoration: line-through;">
                        {% else %}
                        <tr>
                        {% endif %}

                        <td>{{ k.id }}</td>
                        <td>{{ k.doctor_name }}</td>
                        <td>{{ k.doctor_email }}</td>
                        <td>{{ k.city }}</td>
                        <td>{{ k.specialization }}</td>
                        <td>{{ k.booked_date }}</td>
                        <td>{{ k.booked_time }}</td>

                        <td><button class="btn modal-trigger" data-target="p{{k.id}}"><i class="large material-icons large">description</i></button></td>

                    </tr>
                    <div id="p{{k.id}}" class="modal" style="background-color: #90caf9;">
                        <div class="modal-content">

                            {% if k.status == 'Pending' %}
                                <span style="font-size:15;">Status: <span style="color: orange;">{{ k.status }}</span></span>
                            {% else %}
                                <span style="font-size:15;">Status: <span style="color: green;">{{ k.status }}</span></span>
                            {% endif %}
                            <h4>Doctor's Advice:</h4>
                            <h5>{{ k.doctors_advice }}</h5>
                        </div>
                        <div class="modal-footer">
                          <a class="modal-action modal-close btn deep-orange darken-2">Close</a>
                        </div>
                    </div>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
        </div>
        {% else %}
            <h5 class="center">You haven't booked any appointment!!</h5>
        {% endif %}

    </div>
    </div>
    </div>
<script type="text/javascript">
    $(document).ready(function(){
        $('select').formSelect();
        $('.modal').modal();
    });

</script>
{% endblock %}