bookings/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from .views import ShowAppointmentsDoctors, ShowAppointmentsPatients, bookingView, ModifyAppointmentDoctors, DeleteAppointmentView
app_name = 'bookings'

urlpatterns = [
    path('patient/', login_required(ShowAppointmentsPatients, login_url='users:login'), name='show_appointment_patient'),
    path('doctor/', login_required(ShowAppointmentsDoctors, login_url='users:login'), name='show_appointment_doctor'),
    path('', bookingView, name='conform_booking'),

    path('doctor/appointments/<str:pk>/', login_required(ModifyAppointmentDoctors, login_url='users:login'), name='modify_appointment_doctor'),
    path('patient/appointments/delete/<str:pk>/', login_required(DeleteAppointmentView, login_url='users:login'), name='delete_appointment'),
]

customer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('diseases/', include('disease_database.urls')),
    path('bookings/', include('bookings.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

disease_database/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from .views import SearchView, prediction_result_list_view, about_disease, covid19_view
app_name = 'disease_database'

urlpatterns = [
    path('prediction/', login_required(SearchView, login_url='users:login'), name='search'),
    path('prediction/submit/', login_required(prediction_result_list_view, login_url='users:login'), name='submit_symptom'),
    path('prediction/search/', login_required(about_disease, login_url='users:login'), name='disease_info'),

    path('covid-19/', covid19_view, name='covid19'),

]

users/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import (LoginpageView, ProfileView, ProfileViewPK, DoctorSignupView, PatientSignupView,
                    PatientProfileUpdateView, DoctorProfileUpdateView, ChangePasswordView)

app_name = 'users'

urlpatterns = [
    path('login/', LoginpageView, name='login'),

    path('logout/', auth_views.LogoutView.as_view(next_page='/accounts/login'), name='logout'),

    path('profile/', login_required(ProfileView, login_url='users:login'), name='profile'),
    path('profile/<int:pk>/', login_required(ProfileViewPK, login_url='users:login'), name='profile_with_pk'),
    # path('Dprofile', login_required(ProfileView), name='Dprofile'),

    path('doctor/registration/', DoctorSignupView, name='doctor_registration'),
    path('patient/registration/', PatientSignupView, name='patient_registration'),

    path('Patient/update/', login_required(PatientProfileUpdateView, login_url='users:login'), name='Pupdateprofile'),
    path('Doctor/update/', login_required(DoctorProfileUpdateView, login_url='users:login'), name='Dupdateprofile'),

    path('change_password/', login_required(ChangePasswordView, login_url='users:login'), name='ChangePassword'),
]

bookings/models.py
from django.db import models
from users.models import ExtendedDoctorsDetail, ExtendedPatientsDetail
# Create your models here.


class Booking(models.Model):
    status_options = (('Pending', 'Pending'),
                      ('Attended', 'Attended'))
    p_id = models.IntegerField(null=True)
    patient_name = models.CharField(max_length=30, null=True)
    patient_email = models.CharField(max_length=50, null=True)
    patient_age = models.CharField(max_length=2, null=True)

    d_id = models.IntegerField(null=True)
    doctor_name = models.CharField(max_length=30, null=True)
    doctor_email = models.CharField(max_length=50, null=True)
    specialization = models.CharField(max_length=50, null=True)
    city = models.CharField(max_length=100, null=True)

    booked_date = models.CharField(max_length=50, null=True)
    booked_time = models.CharField(max_length=50, null=True)

    doctors_advice = models.TextField(max_length=200, null=True, default='None')
    status = models.CharField(max_length=20, null=True, choices=status_options, default='Pending')

    '''def __str__(self):
        return self.patient_name'''

base/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href = "https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"rel = "stylesheet">
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    {% block title %}
    {% endblock %}
    <style type="text/css">
        .activeLink{
        background-color: grey;
            height:60px;
            margin-top: 4px;
            border-bottom: solid 5px blue;
        }
        li a{
            font-size: 20px;
        }
        #id_doctors_advice{
            height: 100px;
        }
        ui-datepicker {font-size:64%; }
        ::-webkit-input-placeholder { /* WebKit browsers */
                color: black;
                opacity: 1;
                font-style: italic;

            placeholder{
                color:   white;
            }
            .deleteButton{
                padding:5px 5px 5px 13px; cursor: pointer;
            }
            .chip{
                font-weight: 700;
                font-size: 15px;
                background-color: rgba(255, 255, 255, 0.986);
            }
            header{
                font-size: 15px;
                font-weight: 500;
                color: white;
            }
            .btn-floating{
                font-size: 13px;
                margin: 5px 2px 2px 20px;
            }
            .diseaseCard{
                background-color: rgba(245, 245, 245, 0.534);
                padding: 5px 50px;
                margin: 10px 20px;
                width: 80%;
            }
        .error{
            color: red;
        }
        .success{
            color: green;
        }
        .helper-text{
            font-style: italic;
        }

        .loader{
        background: white;
        position: fixed;
        height: 100%;
        width: 100%;
        z-index: 99;
        display: block;
        justify-content: center;
        align-items: center;
      }
      .loader > div{
        width: 60%;
      }
      .loader.hidden{
        animation: fadeOut 1s;
        animation-fill-mode: forwards;
      }
      @keyframes fadeOut{
        100% {
          opacity: 0;
          visibility: hidden;
        }
      }
      .collapsible-header {
        font-weight:500;
      }
      input:disabled {
        color: black;
      }
    </style>
</head>
<body>
    {% load static %}
    <div class="loader" style="height:100%; display:flex; z-index:99;" id="loader"></div>
    {% block body %}
    {% endblock %}

    {% block sidenav %}
        <script type="text/javascript">
           $(document).ready(function(){
                $('.sidenav').sidenav();
             });
        </script>
    {% endblock %}

    {% block footer %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    {% endblock %}
    <script src="{% static 'js/loader.js' %}"></script>
</body>
</html>

base/templates/navBar.html
{% load i18n %}
<div class="navbar-fixed">
 <nav class="" style="background-color:#008080; margin-bottom: 3px;">
    <div class="nav-wrapper" style="margin-right: 20px; margin-left: 30px;">
        <a href="#" class="brand-logo hide-on-med-and-down">EDP & ABS</a>
        <a href="#"style="font-size:25px;" data-target="mobile-demo" class="sidenav-trigger right">&#9776;</a>
        <ul class="right hide-on-med-and-down">
            <li><a style="color: red; font-weight:600; display: flex;" href="{% url 'disease_database:covid19' %}" {% if request.path == '/diseases/covid-19/'%} class="activeLink" {% endif %} class="left"><i class="material-icons">healing</i>CoVid-19</a></li>
          {% if user.is_authenticated %}

            {% if user.is_patient %}
                <li><a style="display: flex;" href="{% url 'disease_database:search' %}"  {% if request.path == '/diseases/prediction/' %} class="activeLink" {% endif %}><i class="tiny material-icons ">search</i> Disease Prediction</a></li>
                <li><a style="display: flex;" href="{% url 'bookings:conform_booking' %}"{% if request.path == '/bookings/' %} class="activeLink" {% endif %}><i class="material-icons ">add_box</i> Book Appointment</a></li>
                <li><a style="display: flex;" href="{% url 'bookings:show_appointment_patient' %}"{% if request.path == '/bookings/patient/' %} class="activeLink" {% endif %}><i class="material-icons ">book </i> My Bookings</a></li>

                <li><a style="display: flex; color: navy; font-weight:600; font-style: italic;" href="{% url 'users:profile' %}"{% if request.path == '/accounts/profile/' %} class="activeLink" {% endif %}><i class="material-icons">person</i>{{ request.user.name }}</a></li>
            {% elif user.is_doctor %}
                <li><a style="display: flex;" href="{% url 'bookings:show_appointment_doctor' %}"{% if request.path == '/bookings/doctor/' %} class="activeLink" {% endif %}><i class="material-icons ">book</i >My Appointments</a></li>
                <li style="width:100px;"></li>
                <li><a style="font-weight:600; color: navy; display: flex; font-style: italic;" href="{% url 'users:profile' %}"{% if request.path == '/accounts/profile/' %} class="activeLink" {% endif %}><i class="material-icons">person</i>{{ request.user.name }}</a></li>
            {% else %}

            {% endif %}

            <li><a style="font-weight:600; font-style: bold; color:red; display: flex;" href="{% url 'users:logout' %}"><i class="tiny material-icons ">power_settings_new </i> Logout</a></li>
          {% else %}
            <li><a href="{% url 'users:login' %}" {% if request.path == '/accounts/login/' %} class="activeLink" {% endif %}>Login</a></li>
          {% endif %}
      </ul>
    </div>
  </nav>
</div>
<ul class="sidenav" id="mobile-demo">
    <li><a style="color: red; font-weight:600; display: flex;" href="{% url 'disease_database:covid19' %}"><i class="material-icons red-text">healing</i>CoVid-19</a></li>
          {% if user.is_authenticated %}
            {% if user.is_patient %}
                <li><a style="font-weight:600; color: #2196f3; font-style: italic;" href="{% url 'users:profile' %}"{% if request.path == '/accounts/profile/' %} class="activeLink" {% endif %}><i class="material-icons blue-text">person</i>{{ request.user.name }}</a></li>
                <li><a href="{% url 'disease_database:search' %}"{% if request.path == '/prediction/' %} class="activeLink" {% endif %}><i class="material-icons ">search</i>Disease Prediction</a></li>
                <li><a href="{% url 'bookings:conform_booking' %}"{% if request.path == '/bookings/' %} class="activeLink" {% endif %}><i class="material-icons ">add_box</i>New Appointment</a></li>
                <li><a href="{% url 'bookings:show_appointment_patient' %}"{% if request.path == '/bookings/patient/' %} class="activeLink" {% endif %}><i class="material-icons ">book</i>My Bookings</a></li>
            {% elif user.is_doctor %}
                <li><a style="font-weight:600;  color: #2196f3; font-style: italic;" href="{% url 'users:profile' %}"{% if request.path == '/accounts/profile/' %} class="activeLink" {% endif %}><i class="material-icons blue-text">person</i>{{ request.user.name }}</a></li>
                <li><a href="{% url 'bookings:show_appointment_doctor' %}"{% if request.path == '/bookings/doctor/' %} class="activeLink" {% endif %}><i class="material-icons ">add_box</i>My Appointments</a></li>
            {% else %}

            {% endif %}

            <li><a style="font-weight:600; font-style: bold; color:red;" href="{% url 'users:logout' %}"><i class="material-icons red-text">power_settings_new</i>Logout</a></li>
          {% else %}
            <li><a href="{% url 'users:login' %}"{% if request.path == '/accounts/login/' %} class="activeLink" {% endif %}>Login</a></li>
          {% endif %}
      </ul>